version: '3.7'
services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - MONGO_URI=mongodb://mongodb/image_scaler
      - MAX_UPLOAD_SIZE=5048576
    networks:
      - image-scaler
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:5.0.4
    restart: always
    networks:
      image-scaler:
        aliases:
          - 'redis'
  mongodb:
    image: mongo:4.0
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      image-scaler:
        aliases:
          - mongodb
networks:
  image-scaler:
volumes:
  mongodb: